// Why: updater, support, and install surfaces must move together when the
// canonical product repository changes.
export const AGENTSTART_GITHUB_REPOSITORY_OWNER = 'xinyao27'
export const AGENTSTART_GITHUB_REPOSITORY_NAME = 'agentstart'
export const AGENTSTART_GITHUB_REPOSITORY_SLUG = `${AGENTSTART_GITHUB_REPOSITORY_OWNER}/${AGENTSTART_GITHUB_REPOSITORY_NAME}`
export const AGENTSTART_GITHUB_REPOSITORY_HOST_PATH = `github.com/${AGENTSTART_GITHUB_REPOSITORY_SLUG}`
export const AGENTSTART_GITHUB_REPOSITORY_URL = `https://${AGENTSTART_GITHUB_REPOSITORY_HOST_PATH}`
export const AGENTSTART_GITHUB_RELEASES_URL = `${AGENTSTART_GITHUB_REPOSITORY_URL}/releases`
export const AGENTSTART_GITHUB_RELEASE_DOWNLOADS_URL = `${AGENTSTART_GITHUB_RELEASES_URL}/download`
export const AGENTSTART_GITHUB_LATEST_RELEASE_DOWNLOAD_URL = `${AGENTSTART_GITHUB_RELEASES_URL}/latest/download`
export const AGENTSTART_GITHUB_ISSUES_URL = `${AGENTSTART_GITHUB_REPOSITORY_URL}/issues`
export const AGENTSTART_GITHUB_STARGAZERS_URL = `${AGENTSTART_GITHUB_REPOSITORY_URL}/stargazers`
