#![forbid(unsafe_code)]
#![recursion_limit = "512"]

pub mod agent_trust;
pub mod entry;
pub mod hosts;
pub mod mobile;
pub mod protocol;
pub mod reverse_protocol;
pub mod runtime;
pub mod transport;
pub mod workspace_ports;

mod account_usage;
mod agent_arguments;
mod agent_status_hooks;
mod ai_vault;
mod app_control;
mod atomic_file_replace;
mod cli;
mod cli_installer;
mod client_events;
mod clipboard;
mod computer;
mod crash_reports;
mod dangerous_approval;
mod developer_permissions;
mod diagnostics;
mod emulator;
mod external_paths;
mod feedback;
mod files;
mod folder_workspaces;
mod git;
mod github;
mod host_progress;
mod host_registry;
mod http_client;
mod keybindings;
mod latest_snapshot;
mod layouts;
mod local_download;
mod native_messaging;
mod notebook;
mod notifications;
mod orchestration;
mod paths;
mod persistence;
mod preflight;
mod process_liveness;
mod profiles;
mod project_groups;
mod project_host_setups;
pub mod projects;
mod provider_usage;
mod redaction;
mod repo_host;
mod repositories;
mod repository_refs;
mod ritual;
mod rpc;
mod runtime_environment;
mod runtime_metadata;
mod runtime_path;
mod session_tabs;
mod settings;
mod shell_events;
mod shell_files;
mod shell_platform;
mod shell_services;
mod shell_state;
mod skills;
mod star_nag;
mod telemetry;
mod terminal_scrollback;
mod terminal_session;
mod ui;
mod update;
mod updater;
mod workspace_cleanup;
mod workspace_paths;
mod workspace_session;
mod workspace_space;
mod worktree_labels;
mod worktrees;
