mod accounts;
mod agent_session;
mod agent_status;
mod agent_trust;
mod ai_vault;
mod app_control;
mod artifact;
mod browser_command;
mod browser_protocol;
mod browser_replay;
mod browser_writeback;
pub(crate) mod channel;
mod cli;
mod client_events;
mod clipboard;
mod computer;
mod crash_reports;
mod dangerous_approval;
mod developer_permissions;
mod diagnostics;
mod driver_events;
mod emulator;
mod external_editor;
mod feedback;
mod files;
mod folder_workspace;
mod git;
mod github;
mod host_progress;
mod host_registry;
mod keybindings;
mod layout;
mod local_download;
mod markdown;
mod mobile;
mod notebook;
mod notifications;
mod orchestration;
mod preflight;
mod profiles;
mod project;
mod project_context;
mod project_group;
mod project_host_setup;
mod protocol_call;
mod protocol_calls;
mod protocol_connection;
mod protocol_duplex;
pub(crate) mod protocol_reverse;
mod protocol_session;
mod provider_usage;
pub(crate) mod rate_limit_resume;
mod repo;
pub(crate) use repo::protocol_values::repo_value as protocol_repo_value;
pub(crate) use workspace_events::protocol_values::event_value as protocol_workspace_event_value;
mod repo_host;
mod repository_refs;
mod ritual;
mod runtime_environment;
mod services;
mod session;
mod session_tabs;
mod settings;
mod shell_events;
mod shell_files;
mod shell_platform;
mod shell_runtime;
mod shell_state;
mod shell_telemetry;
mod skills;
mod star_nag;
mod stats;
mod status;
mod terminal;
mod ui;
mod updater;
mod visual_regression;
mod windows_firewall;
mod workspace_cleanup;
mod workspace_events;
mod workspace_ports;
mod workspace_session;
mod workspace_space;
mod worktree;
mod worktree_labels;
mod zod_input;

pub(crate) use agent_session::{
    AgentSessionAuthority, AgentSessionLaunchError, AgentSessionLaunchRequest,
};
pub(crate) use agent_status::{AgentStatusAuthority, AgentStatusFlushError};
pub use channel::AuthenticatedChannel;
pub(crate) use services::{SessionServiceInputs, SessionServices};
pub(crate) use session::{SessionError, run_session};
