export const FEATURE_INTERACTION_IDS = [
  'workspace-agent-sessions',
  'cmd-j',
  'cmd-j-workspace-open',
  'cmd-j-browser-page-open',
  'cmd-j-settings-open',
  'cmd-j-quick-action',
  'cmd-j-create-workspace',
  'browser',
  'browser-tab-created',
  'browser-annotations',
  'browser-annotations-sent-to-agent',
  'browser-grab',
  'markdown-file-created',
  'workspace-creation',
  'agent-browser-setup',
  'agent-browser-use',
  'agent-orchestration-setup',
  'agent-orchestration',
  'mobile-emulator-agent-setup',
  'ai-commit-generation',
  'ai-pr-generation',
  'claude-account-switching',
  'computer-use-setup',
  'computer-use',
  'codex-account-switching',
  'cookie-import',
  'mobile-pairing',
  'notifications',
  'ports',
  'quick-commands',
  'resource-manager',
  'review-notes',
  'terminal-pane-split',
  'terminal-panes',
  'terminal-tabs',
  'tab-splits',
  'usage-tracking',
  'workspace-cleanup'
] as const

export type FeatureInteractionId = (typeof FEATURE_INTERACTION_IDS)[number]
