#!/usr/bin/env bash
# Why: release publishing spans npm, Chrome Web Store, and Apple credentials that
# require one-time browser setup and must be stored in GitHub rather than a developer checkout.
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPOSITORY="xinyao27/agentstart"
EXPECTED_APPLE_TEAM_ID="8H6Q2YA365"
IOS_APP_STORE_APP_ID="6810343597"
IOS_BUNDLE_ID="com.xinyao27.agentstart.mobile"
MACOS_BUNDLE_ID="com.xinyao27.agentstart.macos"
MACOS_APP_STORE_APP_ID="6810480610"

require_nonempty() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    warn "$name cannot be empty."
    exit 1
  fi
}

require_nonempty_file() {
  local label="$1" path="$2"
  if [[ ! -s "$path" ]]; then
    warn "No non-empty $label file exists at that path."
    exit 1
  fi
}

has_repo_secret() {
  gh secret list --repo "$REPOSITORY" --json name --jq '.[].name' 2>/dev/null |
    grep -Fxq "$1"
}

banner "AgentStart release setup"

stage "GitHub release access"
say "We'll verify GitHub CLI access for release credentials."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is not authenticated. Run: gh auth login"
  exit 1
fi
resolved_repo=$(gh repo view --json nameWithOwner --jq '.nameWithOwner')
if [[ "$resolved_repo" != "$REPOSITORY" ]]; then
  warn "This directory resolves to $resolved_repo, expected $REPOSITORY."
  exit 1
fi
pause "Continue to registry credentials?"

stage "npm first publication"
if npm view @agentstart/cli version >/dev/null 2>&1; then
  say "@agentstart/cli already exists; use npm Trusted Publishing instead of a long-lived token."
  open_url "https://www.npmjs.com/package/@agentstart/cli"
  step "Open Package Settings → Trusted publishing and add a GitHub Actions publisher."
  step "Set organization/user to xinyao27, repository to agentstart, and workflow filename to daemon-release.yml."
  step "Leave environment empty and allow the npm publish action."
  note "Remove NPM_TOKEN after Trusted Publishing is configured and one release succeeds through it."
elif has_repo_secret NPM_TOKEN; then
  say "NPM_TOKEN already exists; leaving it unchanged."
else
  say "The @agentstart/cli package does not exist yet, so its first CI publication needs a token."
  open_url "https://www.npmjs.com/"
  step "Sign in and confirm your account can publish public packages under the @agentstart scope."
  step "Open your avatar → Access Tokens → Generate New Token → Granular Access Token."
  step "Grant read/write package access for @agentstart, enable publishing 2FA bypass, and generate it."
  step "Copy the token now; npm will not display the complete value again."
  ask_secret NPM_TOKEN "Paste the npm token:"
  if [[ -z "$NPM_TOKEN" ]]; then
    warn "NPM_TOKEN cannot be empty."
    exit 1
  fi
  set_secret NPM_TOKEN "$NPM_TOKEN"
fi
note "After the first release, replace this token with npm Trusted Publishing as documented."
pause "Continue to product telemetry?"

stage "Product telemetry"
if has_repo_secret POSTHOG_WRITE_KEY; then
  say "POSTHOG_WRITE_KEY already exists; leaving it unchanged."
else
  say "Stable daemon builds require the PostHog project API key at compile time."
  open_url "https://us.posthog.com/"
  step "Create or select the US project that will receive AgentStart product events and support reports."
  step "Open Project settings and copy the Project API Key, not a personal API key."
  step "Review the project's event retention and deletion settings for the published privacy policy."
  ask_secret POSTHOG_WRITE_KEY "Paste the PostHog Project API Key:"
  require_nonempty POSTHOG_WRITE_KEY "$POSTHOG_WRITE_KEY"
  set_secret POSTHOG_WRITE_KEY "$POSTHOG_WRITE_KEY"
fi
pause "Continue to Apple distribution credentials?"

stage "Apple distribution"
say "AgentStart releases use Apple team $EXPECTED_APPLE_TEAM_ID."
open_url "https://developer.apple.com/account/resources/identifiers/list"
step "Confirm the two App IDs and shared App Group in apps/mobile/RELEASE.md exist with their listed capabilities."
step "Confirm the registered explicit App ID AgentStart macOS uses bundle ID $MACOS_BUNDLE_ID."
open_url "https://appstoreconnect.apple.com/apps"
step "Confirm App Store Connect app $IOS_APP_STORE_APP_ID uses bundle ID $IOS_BUNDLE_ID."
step "Do not add macOS to that iOS record: Apple would require its macOS target to use $IOS_BUNDLE_ID."
step "Confirm macOS-only app $MACOS_APP_STORE_APP_ID is named AgentStart for Mac, uses bundle ID $MACOS_BUNDLE_ID, and uses SKU agentstart-macos."
step "Confirm macOS App Store version 1.0 exists only as the reserved store version and has no current Developer ID build attached."
note "The current Developer ID DMG needs no App Store Connect record and must not be uploaded as a store build."
note "apps/macos/APP-STORE.md records the sandbox blockers and the target split required before upload."
APPLE_RELEASE_SECRETS=(
  APPLE_APP_SPECIFIC_PASSWORD
  APPLE_ID
  APPLE_TEAM_ID
  APP_STORE_APP_ID
  ASC_API_KEY_P8
  ASC_ISSUER_ID
  ASC_KEY_ID
  IOS_DIST_CERT_P12
  IOS_DIST_CERT_PASSWORD
  MAC_CERTS
  MAC_CERTS_PASSWORD
)
missing_apple_release_secret=0
for name in "${APPLE_RELEASE_SECRETS[@]}"; do
  if ! has_repo_secret "$name"; then
    missing_apple_release_secret=1
    break
  fi
done
if [[ "$missing_apple_release_secret" == 0 ]]; then
  say "All iOS, macOS, and notarization credentials already exist; leaving them unchanged."
else
  open_url "https://appstoreconnect.apple.com/access/integrations/api"
  step "Use an App Store Connect Admin API key, then copy its Key ID and Issuer ID."
  step "Download its .p8 file now; Apple only allows the private key to be downloaded once."
  if ! has_repo_secret ASC_KEY_ID; then
    ask ASC_KEY_ID "Paste the App Store Connect API Key ID:"
    require_nonempty ASC_KEY_ID "$ASC_KEY_ID"
    set_secret ASC_KEY_ID "$ASC_KEY_ID"
  fi
  if ! has_repo_secret ASC_ISSUER_ID; then
    ask ASC_ISSUER_ID "Paste the App Store Connect API Issuer ID:"
    require_nonempty ASC_ISSUER_ID "$ASC_ISSUER_ID"
    set_secret ASC_ISSUER_ID "$ASC_ISSUER_ID"
  fi
  if ! has_repo_secret ASC_API_KEY_P8; then
    ask ASC_API_KEY_P8_PATH "Paste the path to the downloaded App Store Connect .p8 file:"
    require_nonempty_file "App Store Connect key" "$ASC_API_KEY_P8_PATH"
    ASC_API_KEY_P8=$(base64 < "$ASC_API_KEY_P8_PATH" | tr -d '\n')
    set_secret ASC_API_KEY_P8 "$ASC_API_KEY_P8"
  fi

  if ! has_repo_secret APPLE_TEAM_ID; then
    set_secret APPLE_TEAM_ID "$EXPECTED_APPLE_TEAM_ID"
  fi
  if ! has_repo_secret APP_STORE_APP_ID; then
    set_secret APP_STORE_APP_ID "$IOS_APP_STORE_APP_ID"
  fi

  if ! has_repo_secret IOS_DIST_CERT_P12; then
    open_url "https://developer.apple.com/account/resources/certificates/list"
    step "Create or select an Apple Distribution certificate for the AgentStart team."
    step "Export the certificate and its private key from Keychain Access as a password-protected .p12."
    ask IOS_DIST_CERT_P12_PATH "Paste the path to the Apple Distribution .p12 file:"
    require_nonempty_file "Apple Distribution certificate" "$IOS_DIST_CERT_P12_PATH"
    IOS_DIST_CERT_P12=$(base64 < "$IOS_DIST_CERT_P12_PATH" | tr -d '\n')
    set_secret IOS_DIST_CERT_P12 "$IOS_DIST_CERT_P12"
  fi
  if ! has_repo_secret IOS_DIST_CERT_PASSWORD; then
    ask_secret IOS_DIST_CERT_PASSWORD "Paste the Apple Distribution .p12 password:"
    require_nonempty IOS_DIST_CERT_PASSWORD "$IOS_DIST_CERT_PASSWORD"
    set_secret IOS_DIST_CERT_PASSWORD "$IOS_DIST_CERT_PASSWORD"
  fi

  if ! has_repo_secret MAC_CERTS; then
    open_url "https://developer.apple.com/account/resources/certificates/list"
    step "Create or select a Developer ID Application certificate for the AgentStart team."
    step "Export the certificate and its private key from Keychain Access as a password-protected .p12."
    ask MAC_CERTS_PATH "Paste the path to the Developer ID Application .p12 file:"
    require_nonempty_file "Developer ID Application certificate" "$MAC_CERTS_PATH"
    MAC_CERTS=$(base64 < "$MAC_CERTS_PATH" | tr -d '\n')
    set_secret MAC_CERTS "$MAC_CERTS"
  fi
  if ! has_repo_secret MAC_CERTS_PASSWORD; then
    ask_secret MAC_CERTS_PASSWORD "Paste the Developer ID Application .p12 password:"
    require_nonempty MAC_CERTS_PASSWORD "$MAC_CERTS_PASSWORD"
    set_secret MAC_CERTS_PASSWORD "$MAC_CERTS_PASSWORD"
  fi

  if ! has_repo_secret APPLE_ID || ! has_repo_secret APPLE_APP_SPECIFIC_PASSWORD; then
    open_url "https://account.apple.com/account/manage"
    step "Generate an app-specific password for notarytool under Sign-In and Security."
  fi
  if ! has_repo_secret APPLE_ID; then
    ask APPLE_ID "Paste the Apple Account email used for notarization:"
    require_nonempty APPLE_ID "$APPLE_ID"
    set_secret APPLE_ID "$APPLE_ID"
  fi
  if ! has_repo_secret APPLE_APP_SPECIFIC_PASSWORD; then
    ask_secret APPLE_APP_SPECIFIC_PASSWORD "Paste the app-specific password:"
    require_nonempty APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"
    set_secret APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"
  fi
fi
note "Fastlane rejects any APP_STORE_APP_ID other than iOS AgentStart record $IOS_APP_STORE_APP_ID."
finish
